name: Deploy Next.js to Server

on:
  push:
    branches: [ release ] # 只在 main 分支推送时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22 # 使用你项目所需的 Node.js 版本
        
    - name: Install dependencies
      run: npm install
      
    - name: Build project
      run: npm run build
      
    - name: Create deployment package
      run: |
        mkdir -p deployment/.next
        cp -r .next/ deployment/.next/
        cp -r public/ deployment/public/
        cp package*.json deployment/
        cp next.config.js deployment/ # 如果有的话
        
    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        source: "deployment/"
        target: "/path/to/your/project/on/server"
        
    - name: Install dependencies and restart on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        script: |
          cd /path/to/your/project/on/server
          npm install --production
          pm2 restart your-app-name || pm2 start npm --name "your-app-name" -- start